# This is the same as Dockerfile, but skips `dep ensure`.
# It assumes you already ran that locally.
FROM golang:1.10-alpine AS build

COPY . /go/src/github.com/danisla/terraform-operator/
WORKDIR /go/src/github.com/danisla/terraform-operator/cmd/terraform-operator
RUN go install

FROM alpine:3.7
RUN apk add --update ca-certificates bash curl
COPY --from=build /go/bin/terraform-operator /usr/bin/
CMD ["/usr/bin/terraform-operator"]