apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-apply
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: terraform
      containers:
      - name: terraform
        image: gcr.io/cloud-solutions-group/terraform-job:latest
        env:
        - name: JOB_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['job-name']
        volumeMounts:
        - name: state
          mountPath: /opt/terraform/.terraform
        - name: config
          mountPath: /opt/terraform/main.tf
          subPath: main.tf
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: terraform-config
          items:
          - key: main.tf
            path: main.tf
      - name: state
        emptyDir: {}
  