apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-operator
  namespace: metacontroller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terraform-operator
subjects:
- kind: ServiceAccount
  name: terraform-operator
  namespace: metacontroller
roleRef:
  kind: ClusterRole
  name: terraform-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terraform-operator
  namespace: metacontroller
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: ["ctl.isla.solutions"]
  resources: ["*"]
  verbs: ["*"]
---
# Terraform Pod RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terraform
subjects:
- kind: ServiceAccount
  name: terraform
  namespace: default
roleRef:
  kind: ClusterRole
  name: terraform
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terraform
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","patch"]