apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-operator
  namespace: metacontroller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terraform-operator
subjects:
- kind: ServiceAccount
  name: terraform-operator
  namespace: metacontroller
roleRef:
  kind: ClusterRole
  name: terraform-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: terraform-operator
  namespace: metacontroller
rules:
- apiGroups: ["", "batch"] # "" indicates the core API group
  resources: ["configmaps", "jobs"]
  verbs: ["*"]