steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloud-solutions-group/terraform-job:latest', '.']
  dir: './terraform-job'
images: ['gcr.io/cloud-solutions-group/terraform-job:latest']
